survey_survey:
    resource: "@SurveyBundle/Resources/config/routing/survey.yml"
    prefix:   /admin/survey

survey_homepage:
    path:     /
    defaults: { _controller: SurveyBundle:Default:index }
